- name: Installing EPEL
  become: yes
  package:
    name: "epel-release"
    state: present

- name: Installing packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - autoconf
    - automake
    - gcc
    - git
    - libX11-devel
    - libXinerama-devel
    - libXrandr-devel
    - libev-devel
    - libxcb-devel
    - libxkbcommon-devel
    - libxkbcommon-x11-devel
    - make
    - pango-devel
    - pcre-devel
    - startup-notification-devel
    - wget
    - "xcb-util*-devel"
    - xcb-util-cursor-devel
    - xcb-util-devel
    - xcb-util-keysyms-devel
    - xcb-util-wm-devel
    - "xorg-x11-font*"
    - xorg-x11-util-macros
    - xterm
    - yajl-devel

# i3 gaps :
# https://gist.github.com/stevommmm/5cfe41429579b07862b5f68942915ed2
## Build and install xcb-util-xrm first
## xcb-util-xrm dependencies : xcb-util-devel
## Dependencies : libxcb-devel xcb-util-keysyms-devel xcb-util-devel xcb-util-wm-devel yajl-devel libXrandr-devel startup-notification-devel libev-devel xcb-util-cursor-devel libXinerama-devel libxkbcommon-devel libxkbcommon-x11-devel pcre-devel pango-devel git gcc automake

# git clone --recursive https://github.com/Airblader/xcb-util-xrm 
# cd xcb-util-xrm
# git submodule update --init
# ./autogen.sh --prefix=/usr --libdir=/usr/lib64
# make
# make install

# curl -OL https://github.com/Airblader/i3/archive/$VERSION.tar.gz -O i3.tar.gz
# tar xvzf i3.tar.gz 
# cd i3-$VERSION/ 
# autoreconf --force --install 
# mkdir -p build 
# cd build/ 
# ../configure --prefix=/usr --sysconfdir=/etc --disable-sanitizers 
# make 
# make install

######## OLD DEPENDENCIES #########
    # - autoconf
    # - automake
    # - bison
    # - cmake
    # - file
    # - finger
    # - flex
    # - gcc
    # - gcc-c++
    # - gettext
    # - libtool
    # - libX11-devel
    # - libXfixes-devel
    # - libjpeg-devel
    # - libXrandr-devel
    # - libxslt
    # - nasm
    # - make
    # - openssl-devel
    # - pam-devel
    # - patch
    # - perl-libxml-perl
    # - pkgconfig
    # - xmlto-tex
    # - xorg-x11-font-utils
    # - xorg-x11-server-Xorg
    # - xorg-x11-server-devel
    # - xorg-x11-xinit
    # - libXfont2
    # - libXfont2-devel
    # - doxygen
    # # oui
    # - libxcb-devel
    # - xcb-util-keysyms-devel
    # - xcb-util-devel
    # - xcb-util-wm-devel
    # - yajl-devel
    # - libXrandr-devel
    # - startup-notification-devel
    # - libev-devel
    # - xcb-util-cursor-devel
    # - libXinerama-devel
    # - libxkbcommon-devel
    # - libxkbcommon-x11-devel
    # - pcre-devel
    # - pango-devel
    # - git
    # - gcc automake