- name: Checking EPEL is enabled
  become: yes
  shell: yum repolist -t -q 2>/dev/null | tail -n +2 | grep -i "epel"
  register: epel_installed
  changed_when: false
  failed_when: false
  args:
    warn: no

- assert:
    that: epel_installed.rc == 0

- name: Installing packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - asciidoc
    - autoconf
    - automake
    - gcc
    - git
    - libX11-devel
    - libXinerama-devel
    - libXrandr-devel
    - libev-devel
    - libxcb-devel
    - libxkbcommon-devel
    - libxkbcommon-x11-devel
    - make
    - pango-devel
    - pcre-devel
    - startup-notification-devel
    - wget
    - "xcb-util*-devel"
    - xcb-util-cursor-devel
    - xcb-util-devel
    - xcb-util-keysyms-devel
    - xcb-util-wm-devel
    - "xorg-x11-font*"
    - xorg-x11-util-macros
    - xterm
    - yajl-devel

- name: Removing any i3 package
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  loop:
    - i3
    - i3-doc
    - i3lock
    - i3status

- name: Installing xcb-xrm
  become: yes
  unarchive:
    src: http://149.202.50.118/xcb-util-xrm-x86-x64-el7.tgz
    dest: /
    remote_src: yes
    creates: /usr/lib64/libxcb-xrm.so

# i3 gaps :
# https://gist.github.com/stevommmm/5cfe41429579b07862b5f68942915ed2
