- name: Installing packages
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - autoconf
    - automake
    - gcc
    - git
    - libX11-devel
    - libXinerama-devel
    - libXrandr-devel
    - libev-devel
    - libxcb-devel
    - libxkbcommon-devel
    - libxkbcommon-x11-devel
    - make
    - pango-devel
    - pcre-devel
    - startup-notification-devel
    - wget
    - "xcb-util*-devel"
    - xcb-util-cursor-devel
    - xcb-util-devel
    - xcb-util-keysyms-devel
    - xcb-util-wm-devel
    - "xorg-x11-font*"
    - xorg-x11-util-macros
    - xterm
    - yajl-devel

# i3 gaps :
# https://gist.github.com/stevommmm/5cfe41429579b07862b5f68942915ed2
